# Generated by Django 3.2 on 2022-09-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupChat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
        migrations.AlterField(
            model_name='admin',
            name='group_name',
            field=models.CharField(default='Group_Admin_<function RandomString at 0x00000208FAF084C0>', editable=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='group_name',
            field=models.CharField(default='Group_User_<function RandomString at 0x00000208FAF084C0>', editable=False, max_length=40),
        ),
    ]
