# Generated by Django 3.2 on 2022-09-18 01:21

import SupChat.core.tools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupChat', '0002_auto_20220913_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='group_name',
            field=models.CharField(default=SupChat.core.tools.RandomString, editable=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='group_name',
            field=models.CharField(default=SupChat.core.tools.RandomString, editable=False, max_length=40),
        ),
    ]
