# Generated by Django 3.2 on 2022-09-23 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SupChat', '0003_auto_20220918_0121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='lastSeen',
            new_name='last_seen',
        ),
    ]
