# Generated by Django 3.2 on 2022-09-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupChat', '0004_rename_lastseen_admin_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='is_busy',
        ),
        migrations.AddField(
            model_name='user',
            name='ip',
            field=models.CharField(default='2', max_length=20),
            preserve_default=False,
        ),
    ]
