# Generated by Django 3.2 on 2022-09-24 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SupChat', '0005_auto_20220924_0336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='phone_or_email',
        ),
        migrations.RemoveField(
            model_name='blacklist',
            name='session_key',
        ),
        migrations.AddField(
            model_name='blacklist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SupChat.user'),
            preserve_default=False,
        ),
    ]
