# Generated by Django 3.2 on 2022-09-24 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SupChat', '0006_auto_20220924_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SupChat.user'),
        ),
    ]
