# Generated by Django 3.2 on 2022-09-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupChat', '0008_auto_20220925_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supchatconfig',
            name='end_chat_after',
            field=models.IntegerField(default=30, help_text='پس از مدتی بدون فعالیت چت به صورت خودکار بسته میشود .'),
        ),
        migrations.AlterField(
            model_name='supchatconfig',
            name='end_chat_auto',
            field=models.BooleanField(default=False, help_text='ممکن است گاهی چت بسته نشود(کاربر قبل از زمان معین شده صفحه را ببندد)'),
        ),
    ]
