# Generated by Django 3.2 on 2022-10-03 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SupChat', '0011_rename_notif_message_is_active_supchatconfig_notif_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supchatconfig',
            old_name='default_notif_message_is_active',
            new_name='default_notif_is_active',
        ),
        migrations.RenameField(
            model_name='supchatconfig',
            old_name='default_notif_message_show_after',
            new_name='default_notif_show_after',
        ),
    ]
