# Generated by Django 3.2 on 2022-10-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SupChat', '0014_rename_data_time_create_chatgroup_date_time_create'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatgroup',
            old_name='date_time_create',
            new_name='date_time_created',
        ),
    ]
