# Generated by Django 3.2 on 2022-10-06 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupChat', '0015_rename_date_time_create_chatgroup_date_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='rate_chat',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
