# Generated by Django 3.2 on 2022-10-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupChat', '0017_auto_20221010_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supchatstyle',
            name='theme',
            field=models.CharField(choices=[('/supchat/css/theme/default.css', 'default'), ('/supchat/css/theme/purple.css', 'purple')], default='/supchat/css/theme/default.css', max_length=200),
        ),
    ]
