# Generated by Django 3.2 on 2022-10-14 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SupChat', '0023_remove_supchatstyle_background_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistoryAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(max_length=100)),
                ('date_time_submit', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SupChat.admin')),
            ],
        ),
    ]
