# Generated by Django 3.2 on 2022-10-18 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SupChat', '0024_searchhistoryadmin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchhistoryadmin',
            options={'ordering': ('-id',)},
        ),
        migrations.CreateModel(
            name='NotificationAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_time_submited', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SupChat.admin')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
