# Generated by Django 3.2 on 2022-10-19 15:26

import SupChat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupChat', '0025_auto_20221018_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=SupChat.models.upload_image_admin_chat),
        ),
    ]
