# Generated by Django 3.2 on 2022-10-19 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SupChat', '0026_alter_admin_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='date_time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
