# Generated by Django 3.2 on 2022-10-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupChat', '0027_admin_date_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
