# Generated by Django 3.2 on 2022-10-19 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SupChat', '0028_auto_20221019_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SupChat.admin'),
            preserve_default=False,
        ),
    ]
