# Generated by Django 3.2 on 2022-10-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupChat', '0029_blacklist_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ip',
            field=models.CharField(max_length=60),
        ),
    ]
