# Generated by Django 3.2 on 2022-04-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmessage',
            name='type',
            field=models.CharField(default='Text', editable=False, max_length=10),
        ),
    ]
