# Generated by Django 3.2 on 2022-09-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supchatconfig',
            old_name='transferChatIsActive',
            new_name='default_message_is_active',
        ),
        migrations.AddField(
            model_name='supchatconfig',
            name='default_message',
            field=models.CharField(blank=True, default='\n        پشتیبانی سایت ما در کوتاه ترین زمان ممکن پاسخگوی شما دوست عزیز است لطفا پیام خود را بگذارید .\n    ', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='supchatconfig',
            name='transfer_chat_is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='group_name',
            field=models.CharField(default='Group_User_aZ7wawCHz2PH6kN8rcfHCEwG8', max_length=40),
        ),
    ]
