# Generated by Django 3.2 on 2022-09-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_auto_20220908_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supchatconfig',
            name='default_message',
            field=models.CharField(blank=True, default=' پشتیبانی سایت ما در کوتاه ترین زمان ممکن پاسخگوی شما دوست عزیز است لطفا پیام خود را بگذارید .', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='group_name',
            field=models.CharField(default='Group_User_6ecaRhxv4F4CcplBYgKMJSpvH', max_length=40),
        ),
    ]
