# Generated by Django 3.2 on 2022-04-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_textmessage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmessage',
            name='type',
            field=models.CharField(default='text', editable=False, max_length=10),
        ),
    ]
