# Generated by Django 3.2 on 2022-04-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_alter_textmessage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[('you', 'You'), ('other', 'Other')], max_length=10),
        ),
    ]
