# Generated by Django 3.2 on 2022-09-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_auto_20220908_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supchatstyle',
            old_name='backgroundChat',
            new_name='background_chat',
        ),
        migrations.AddField(
            model_name='supchatstyle',
            name='theme',
            field=models.CharField(choices=[('/supchat/css/theme/default.css', 'default'), ('/supchat/css/theme/blue.css', 'blue')], default='default', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='group_name',
            field=models.CharField(default='Group_User_TeYm70WAO1YVmyR2QXz2JHm2P', max_length=40),
        ),
    ]
