# Generated by Django 3.2 on 2022-09-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0004_auto_20220908_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supchatstyle',
            name='theme',
            field=models.CharField(choices=[('/supchat/css/theme/default.css', 'default'), ('/supchat/css/theme/blue.css', 'blue')], default='/supchat/css/theme/default.css', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='group_name',
            field=models.CharField(default='Group_User_ZqiM0NXXx2hv79oahbzi5NySg', max_length=40),
        ),
    ]
