# Generated by Django 3.2 on 2022-04-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0004_alter_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[('section', 'Section'), ('user', 'User')], max_length=10),
        ),
    ]
