# Generated by Django 3.2 on 2022-09-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0005_auto_20220908_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supchatstyle',
            name='theme',
            field=models.CharField(choices=[('/supchat/css/theme/default.css', 'default')], default='/supchat/css/theme/default.css', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='group_name',
            field=models.CharField(default='Group_User_W5oCDzbU5N9XDrlCxKE4vMgXk', max_length=40),
        ),
    ]
