# Generated by Django 3.2 on 2022-04-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0005_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
