# Generated by Django 3.2 on 2022-09-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0006_auto_20220909_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='supchatconfig',
            name='show_last_seen',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='group_name',
            field=models.CharField(default='Group_User_UNB0gCFQlwCRdKH0d4JIfNd2V', max_length=40),
        ),
    ]
