# Generated by Django 3.2 on 2022-09-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0007_auto_20220909_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='supchatconfig',
            name='default_message_outside',
            field=models.CharField(blank=True, default='سلام ، چطور میتوانم کمک کنم ؟', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='supchatconfig',
            name='default_message_outside_is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supchatconfig',
            name='default_message_outside_show_after',
            field=models.IntegerField(default=5, help_text='پس از گذشت چند ثانیه نمایش داده شود'),
        ),
        migrations.AlterField(
            model_name='user',
            name='group_name',
            field=models.CharField(default='Group_User_qWjK9SZEvFldEce014bvWGQwh', max_length=40),
        ),
    ]
