# Generated by Django 3.2 on 2022-04-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0008_message_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='status_online',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='lastSeen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status_online',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=10),
            preserve_default=False,
        ),
    ]
