# Generated by Django 3.2 on 2022-04-17 03:41

import Chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0010_alter_supchatstyle_backgroundchat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supchatstyle',
            name='backgroundChat',
            field=models.ImageField(blank=True, null=True, upload_to=Chat.models.upload_image_background_chat),
        ),
    ]
